dependencies:
- name: api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.24
- name: beet
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.29
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: file
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- alias: keycloak-s
  name: keycloak
  repository: https://codecentric.github.io/helm-charts
  version: 7.4.0
- alias: keycloak-db
  name: mysql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 1.6.2
- name: receipt-api
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.18
